# docker-compose.yml
version: '3.8'

services:
  autogen:
    build: .
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_HOST=${LLM_HOST:-http://local-llm:8080}
    ports:
      - "8000:8000"
    networks:
      - autogen-net

  vectordb:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - autogen-net

networks:
  autogen-net:
    driver: bridge



# requirements.txt
pyautogen>=0.2.0
qdrant-client>=1.6.0
python-dotenv>=0.19.0
fastapi>=0.68.0
uvicorn>=0.15.0