
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Configuración básica
homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Madrid

# Configuración MQTT
mqtt:

# sensor: !include sensors.yaml