FROM postgres:15

# Instalar la extensión uuid-ossp
RUN apt-get update && apt-get install -y postgresql-contrib

# Copiar configuraciones
COPY pg_hba.conf /etc/postgresql/pg_hba.conf
COPY postgresql.conf /etc/postgresql/postgresql.conf

# Configurar PostgreSQL
RUN echo "host all all 0.0.0.0/0 scram-sha-256" >> /etc/postgresql/pg_hba.conf

EXPOSE 5432

CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]