FROM postgres:15

# Instalar la extensión uuid-ossp y pgcrypto
RUN apt-get update && apt-get install -y postgresql-contrib

# Copiar configuraciones
COPY pg_hba.conf /etc/postgresql/pg_hba.conf
COPY postgresql.conf /etc/postgresql/postgresql.conf

# Añadir scripts SQL para crear las tablas de control de acceso y auditoría
COPY init_database_schema.sql /docker-entrypoint-initdb.d/
COPY init_database_data.sql /docker-entrypoint-initdb.d/

# Copiar el script de inicialización personalizado
COPY entrypoint.sh /usr/local/bin/

# Hacer el script de entrada ejecutable
RUN chmod +x /usr/local/bin/entrypoint.sh

# Exponer el puerto de PostgreSQL
EXPOSE 5432

# Comando para iniciar PostgreSQL con la configuración personalizada
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
