FROM postgres:15

# Instalar la extensión uuid-ossp y pgcrypto
RUN apt-get update && apt-get install -y postgresql-contrib

# Copiar configuraciones
COPY pg_hba.conf /etc/postgresql/pg_hba.conf
COPY postgresql.conf /etc/postgresql/postgresql.conf


# Copiar script de inicialización
COPY init-db.sql /docker-entrypoint-initdb.d/00-init-db.sql
# Añadir scripts SQL para crear las tablas de control de acceso y auditoría
COPY init_database_schema.sql /docker-entrypoint-initdb.d/01-schema.sql
COPY init_database_data.sql /docker-entrypoint-initdb.d/02-data.sql


# Variables de entorno necesarias
ENV POSTGRES_USER=test_user
ENV POSTGRES_PASSWORD=test_password
ENV POSTGRES_DB=test_db

# Exponer el puerto de PostgreSQL
EXPOSE 5432

# Usar el entrypoint por defecto de la imagen de postgres
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]