FROM postgres:15

# Instalar la extensión uuid-ossp y pgcrypto
RUN apt-get update && apt-get install -y postgresql-contrib

# Copiar configuraciones
COPY pg_hba.conf /etc/postgresql/pg_hba.conf
COPY postgresql.conf /etc/postgresql/postgresql.conf

# Copiar scripts en orden específico
COPY init-db.sql /docker-entrypoint-initdb.d/01-init-db.sql
COPY init_database_schema.sql /docker-entrypoint-initdb.d/02-schema.sql
COPY init_database_data.sql /docker-entrypoint-initdb.d/03-data.sql

EXPOSE 5432

CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]