FROM postgres:15

# Instalar la extensión uuid-ossp y pgcrypto
RUN apt-get update && apt-get install -y postgresql-contrib

# Copiar configuraciones
COPY pg_hba.conf /etc/postgresql/pg_hba.conf
COPY postgresql.conf /etc/postgresql/postgresql.conf

# Configurar PostgreSQL
RUN echo "host all all 0.0.0.0/0 scram-sha-256" >> /etc/postgresql/pg_hba.conf

# Añadir scripts SQL para crear las tablas de control de acceso y auditoría
COPY init_database.sql /docker-entrypoint-initdb.d/

# Establecer la variable de entorno para la clave de cifrado
ENV ENCRYPT_KEY='my_super_secret_key'

EXPOSE 5432

CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]