version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Exponer puerto del backend
    volumes:
      - ./backend:/app # Opcional para desarrollo
    environment:
      - APP_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Exponer puerto del frontend
    volumes:
      - ./frontend:/app # Opcional para desarrollo
    environment:
      - NODE_ENV=production
