version: '3'

services:
  front:
    build:
      context: .
      dockerfile: attendance_system/frontend/Dockerfile
    image: frontend-attendance
    deploy:
      replicas: 1

  back:
    build:
      context: .
      dockerfile: attendance_system/backend/Dockerfile
    image: backend-attendance
    deploy:
      replicas: 2

  db:
    image: test-postgres-encrypted:latest
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1

  redis:
    image: redis:latest
    deploy:
      replicas: 2

volumes:
  db-data:
    driver: local