version: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: attendance_root_token
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/file
    command: server -dev
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  vault-init:
    image: vault:1.13.3
    depends_on:
      vault:
        condition: service_healthy
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=attendance_root_token
    volumes:
      - ./attendance_system/backend/scripts:/scripts
      - ./.env:/app/.env
    command: ["/bin/sh", "-c", "chmod +x /scripts/init-vault.sh && /scripts/init-vault.sh"]

  front:
    build:
      context: ./attendance_system/frontend
      dockerfile: Dockerfile
    image: frontend-attendance
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=attendance_root_token
    depends_on:
      vault-init:
        condition: service_completed_successfully
    deploy:
      replicas: 1

  back:
    build:
      context: ./attendance_system/backend
      dockerfile: Dockerfile
    image: backend-attendance
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=attendance_root_token
    depends_on:
      vault-init:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      replicas: 2

  db:
    image: test-postgres-encrypted:latest
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./attendance_system/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./attendance_system/nginx/conf/conf.d:/etc/nginx/conf.d:ro
      - ./attendance_system/nginx/html:/usr/share/nginx/html:ro
      - ./attendance_system/nginx/static:/usr/share/nginx/static:ro
      - ./attendance_system/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - front
      - back
      - vault
    deploy:
      replicas: 1

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 2

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    depends_on:
      - back

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  db-data:
    driver: local
  vault-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  default:
    driver: bridge