services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    ports:
      - "8123:8123"
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    restart: unless-stopped

  ha-llm-bridge:
    image: ha-llm-bridge
    build:
      context: .
      dockerfile: Dockerfile-bridge
    environment:
      - HA_URL=ws://homeassistant:8123
      - HA_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiMDRmMTRhNTBhMGE0MWI1YjY2YzQzMWE2ZmYxNzNiYiIsImlhdCI6MTc0MDA1NDc1NywiZXhwIjoyMDU1NDE0NzU3fQ.Ex7uELwo_DbxrSFEnx93uvvObgm7XWLuFRrNWXr09Xw
      - OLLAMA_URL=http://ollama:11434
      - CHROMADB_URL=chromadb:8000
    depends_on:
      - homeassistant
      - chromadb
      - ollama
    restart: unless-stopped